### ISSUE TITLE
Investigate Current Monitoring Uses

### ISSUE THREAD

**Issue by schreiaj** [FRC125/NU15#1]
We need to be able to reliably track and react to our current draw. Whether this means we reduce max motor outputs to high draw systems or simply limit what functionality is available we want to know that we can accurately get data.

**Comment by camilo86** [comment]
Run certain things only to an extend? The robot will limit you to a certain amount of functions at a time? For example, when running drivetrain and shooter, do not allow the driver to run another subsystem (This way we don't get our robot to shut off suddenly like in 2014 season). So pretty much just keep track of what subsystems are being used

**Comment by schreiaj** [comment]
Just so we're clear, the crux of the 2014 problems were the frame shorts.

**Comment by gracepetryk** [comment]
would [this](http://first.wpi.edu/FRC/roborio/release/docs/java/classedu_1_1wpi_1_1first_1_1wpilibj_1_1PowerDistributionPanel.html) from the wpilib docs be of any use?

**Comment by camilo86** [comment]
That seems to be useful. I think it will also be useful go keep track of
subsystems that are currently working and sort of have a limit of things
that can run at once. Idk, what do you guys think?

**Comment by schreiaj** [comment]
Let's see what's needed. For now let's ensure we can get current readings from the drive system
