### ISSUE TITLE
New methods in SpeedController

### ISSUE THREAD

**Issue by LoadingPleaseWait** [FRC125/NU15#28]
There are 2 new methods in the `SpeedController` class. This repository will no longer work with the new version of WPILib since the new methods need to be implemented in the `MultiMotor`. To fix this, the `MultiMotor` class in [Lib2585](https://github.com/Impact2585/Lib2585) can be used.

**Comment by camilo86** [comment]
Thanks for the issue! I added the new methods. It should all be compatible now (not going to use the new functionality for now). a232a69ae909fa4327ecef4d4ff10a51efbaa4c3
