### ISSUE TITLE
Implement a Moving Average Filter

### ISSUE THREAD

**Issue by schreiaj** [FRC125/NU15#3]
http://en.wikipedia.org/wiki/Moving_average

Build a class.

**Comment by camilo86** [comment]
Should I still write a cap and band for the gyro heading?

**Comment by schreiaj** [comment]
No.

**Comment by kreeve** [comment]
Just FYI, we can use Java 8 features, so you can do moving average with
streams (
http://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html),
specifically the average() function:
http://docs.oracle.com/javase/tutorial/collections/streams/reduction.html,
if you want to.

**Comment by schreiaj** [comment]
So it'd be: 
`GyroVal = gyroDoubleStream.limit(10).average();`

or something I kinda like Java8. Can we see if there's a performance hit to keeping all those values around?
