### ISSUE TITLE
Implement a better PID controller 

### ISSUE THREAD

**Issue by schreiaj** [FRC125/NU15#5]
http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/

The current controller we're using has some issues, take a peak at this and see if we can improve it. Or, if we can use the WPILib one or steal one from Poofs.

**Comment by OliverMacNeely** [comment]
We replaced the PID controllers with the WPILIB ones and deleted the old class file and anything it applied to.
